### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal-web#22]
The temporalio/web imges weight in around 450MB, which is very large for a web container.
https://hub.docker.com/r/temporalio/web/tags

**Comment by feedmeapples** [comment]
Thanks for filing,
I'm gonna be looking into that during this week

**Comment by feedmeapples** [comment]
created a PR that somewhat reduces the image, however there still can be updates to reduce the image further. Some details from the PR

Added multi-stage builds: 1) builder stage 2) final image stage with just the necessary content
Switched to Jessie-lite image.
protobuf folder now only includes <src> with the .proto files
Reduces image size to 400mb:
~100mb jessie-lite image
~300mb temporal-web.

temporal-web details:
18M dist
266M node_modules
4.0K package.json
12M protobuf
76K server
4.0K server.js
208K temporal-proto
4.0K webpack.config.js

Next:

Possibly switch to node:alpine to save ~40mb
look into ways to reduce node_modules (ps. we already install dependencies with --production switch)

**Comment by hazcod** [comment]
@feedmeapples an idea could be distroless here: https://github.com/GoogleContainerTools/distroless/blob/master/experimental/nodejs/README.md

**Comment by feedmeapples** [comment]
Re-opening the item as it was closed automatically with a PR https://github.com/temporalio/temporal-web/pull/27 that reduces the image size, though i will be making further improvements.

The main point will be reducing the node_modules size, there are few approaches that i want to look into such as npm-shrinkwrap. I'm returning to it after the v.1 release

**Comment by feedmeapples** [comment]
The latest docker image is now 110mb total

![image](https://user-images.githubusercontent.com/11838981/81129351-e730f380-8ef8-11ea-84c9-61583d96b5ef.png)
