### ISSUE TITLE
Filtering by date range fails for workflows older than today

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal-web#23]
Reported by a customer:

If you are viewing CLOSED over "Last 3 hours" you will not get workflows that just closed if they were started yesterday.

**Comment by feedmeapples** [comment]
The attached PR should be fixing this issue. If actually fixes dates processing for timestamps and with that fixed, the filtering issues does seem to appear 
![image](https://user-images.githubusercontent.com/11838981/79167925-7be27e80-7d9d-11ea-8ed3-c6a27f3a2553.png)
