### ISSUE TITLE
All the workflow timestamps is showing 12:00 AM

### ISSUE THREAD

**Issue by sunjiawen** [temporalio/temporal-web#33]
<img width="1642" alt="Screen Shot 2020-05-05 at 10 16 06 AM" src="https://user-images.githubusercontent.com/1476377/81095209-8f26cc80-8eb9-11ea-9d29-306031187920.png">

**Comment by feedmeapples** [comment]
Thank you for reporting the issue!

The fix hasn't been officially released yet, however it is available in the latest docker image: `docker pull temporalio/web:latest`
Here is a screenshot just in case
![image](https://user-images.githubusercontent.com/11838981/81129255-a20cc180-8ef8-11ea-9a9e-7254666de6f8.png)

I would suggest running this image with the latest version of server as well (tagged as :latest, not 0.21.1)

**Comment by feedmeapples** [comment]
Will keep the issue open until there is an official release

**Comment by sunjiawen** [comment]
The latest docker shows 13 INTERNAL: Failed to parse server response, not working

**Comment by feedmeapples** [comment]
> The latest docker shows 13 INTERNAL: Failed to parse server response, not working
it might not work against the older versions of server as there have been updates in grpc contract. Works against the latest server. 

These changes will be included in our next release, we will try to get it out later this week.

**Comment by feedmeapples** [comment]
Pushed new release v0.23.0 that contains the fix docker pull temporalio/web:0.23.0

**Comment by feedmeapples** [comment]
Pushed new release v0.23.0 that contains the fix 
``` bash
docker pull temporalio/web:0.23.0
```
