### ISSUE TITLE
History and Visibility Archival statuses show up incorrectly

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/temporal-web#52]
Namespace's HistoryArchivalStatus and VisibilityArchivalStatus show incorrect data

Repro:
1. Enable History Archival
2. Navigate to Namespace Settings

Expected:
"History Archival" and "Visibility Archival" show Enabled

Actual:
Disabled

**Comment by jchenseated** [comment]
temporal server: recent master
temporal web: 0.25.0 (down grade to 0.23.2 will throw 
```12 UNIMPLEMENTED: unknown service workflowservice.WorkflowService```)
